# The devcontainer.json file defines a build so the Dockerfile is used to build a new image.
# The base image is from Microsoft at https://mcr.microsoft.com/en-us/artifact/mar/devcontainers/javascript-node/tags.
# The name "bookworm" refers to the Debian Bookworm release, which is the base OS for this image, adding the name
# fixes the Linux release used.

FROM mcr.microsoft.com/devcontainers/base:ubuntu
ENV DEBIAN_FRONTEND=noninteractive
WORKDIR /workspace

# Install system dependencies required for building and unpacking Ada tooling
RUN apt-get update && apt-get install -y --no-install-recommends \
    curl \
    jq \
    unzip \
    ca-certificates \
    && rm -rf /var/lib/apt/lists/*

# Add the current latest OpenJDK version along with Maven and Gradle
RUN mapfile -t versions << ( \
    apt-cache search --names-only '^openjdk-[0-9]+-jdk$' \
        | awk '{print $1}' \
        | grep -oP '(?<=^openjdk-)[0-9]+(?=-jdk$)' \
        | sort -n \
    ) \
    && sudo apt-get install -y "openjdk-${versions[-1]}-jdk" maven gradle \
    && 